### ISSUE TITLE
Gradle not detecting modern-mcp

### ISSUE THREAD

**Issue by Justsnoopy30** [ahmed605/Modern-MCP#1]
How do you set this up in IntelliJ Idea and integrate gradle?

**Comment by ahmed605** [comment]
How to achieve this ( Note: Everything in brackets below you can Ignore  ) :

1. Import build.gradle in IntelliJ Idea (from Import project label)

2. Enable Auto Import Option (Check Box) 

3. Click OK/Import Button

4. Wait for Build:Sync to complete

5. Open Gradle Tap (if you can't find it you can display it from View->Tool Windows->Gradle)

6. run (modern-mcp->modern-mcp)->Tasks->mcp->setup

ALSO Hexeption made a video about this : https://www.youtube.com/watch?v=20nqRfHL3us&t=1083s

**Comment by Justsnoopy30** [comment]
Thanks

**Comment by ahmed605** [comment]
> Thanks

You are welcome, did it work for you?

**Comment by Justsnoopy30** [comment]
After going to the gradle panel, it said pre-MCP instead of modern-mcp, even though I downloaded modern-mcp, and in the tasks folder it was under other. I ran setupMCP, but it just gave this error:
`6:46:14 AM: Executing task 'setupMCP'...

CreateProcess error=267, The directory name is invalid
6:46:14 AM: Task execution finished 'setupMCP'.
`

**Comment by ahmed605** [comment]
> After going to the gradle panel, it said pre-MCP instead of modern-mcp, even though I downloaded modern-mcp, and in the tasks folder it was under other. I ran setupMCP, but it just gave this error:
> `6:46:14 AM: Executing task 'setupMCP'...
> 
> CreateProcess error=267, The directory name is invalid
> 6:46:14 AM: Task execution finished 'setupMCP'.`
> Edit: Fixed that, I misread the last instruction and clicked MCP before tasks.
> Edit 2: Can't sync with gradle or run setup task:
> Sync Error: https://pastebin.com/JHhY8MMh
> Setup Task Error: https://pastebin.com/Hkyt6bKt
> Edit 3: It seems to keep referencing pre-mcp even though this is modern-mcp.
> Edit 4: None of the tasks work.
> Edit 5: Not even gradlew.bat works: https://pastebin.com/H1PpRJuY
> Edit 6: gradlew.bat Stacktrace: https://pastebin.com/j2ASHpf0

OK I will check this thing

**Comment by ahmed605** [comment]
I made some change in 1.14.2 branch that can fix this , try it now and tell me if it fixed the problem

**Comment by Justsnoopy30** [comment]
Ok, trying.

**Comment by Justsnoopy30** [comment]
A whole bunch of libraries imported, but sync failed.
Configure project failed: https://pastebin.com/0pn9npGU

**Comment by ahmed605** [comment]
but it worked for me maybe it was an internet problem

**Comment by ahmed605** [comment]
LOG: https://api.travis-ci.org/v3/job/549745682/log.txt

**Comment by ahmed605** [comment]
Try delete your IntelliJ Idea project and re-import build.gradle

**Comment by ahmed605** [comment]
MCP is Compatible with Java 8 and 9 only

**Comment by Justsnoopy30** [comment]
Why doesn't it work on Java 12?

**Comment by ahmed605** [comment]
> Why doesn't it work on Java 12?

I don't know but MinecraftForge Team said that

**Comment by Justsnoopy30** [comment]
Oh ok, so what's the max java release I can use with it?
Also, it seems the main problem with Java 12 is `java.lang.RuntimeException: java.lang.NoSuchFieldException: modifiers`

**Comment by ahmed605** [comment]
Screenshot with Java 8 https://live.staticflickr.com/65535/48120371672_a157855f4d_b.jpg

**Comment by Justsnoopy30** [comment]
I am using AdoptOpenJdk, so this might be related and it references forge gradle, and the last comment says something about it working with a blank project and manually setup forge gradle dependencies:
https://github.com/AdoptOpenJDK/homebrew-openjdk/issues/55

**Comment by Justsnoopy30** [comment]
Ok, I'll try it with Java 8 now, but is there any way to get it working on Java 12, as the last comment on the GitHub issue said? They didn't go into detail.

**Comment by Justsnoopy30** [comment]
Seems to be working so far on Java 8, it's running the setup task.
Is there any way to get it working on Java 12, as the last comment on the GitHub issue (https://github.com/AdoptOpenJDK/homebrew-openjdk/issues/55#issuecomment-483778148) said?

**Comment by ahmed605** [comment]
does it work for you in Java 8

**Comment by ahmed605** [comment]
I will search about Java 12 support BTW this issue (Java 12 support) from ForgeGradle not from Modern-MCP

**Comment by Justsnoopy30** [comment]
Ok.
Question: I added a task for runclient in IntelliJ Idea, how do I configure the Gradle task it runs (runclient) so I can change the startup arguments?
Question 2: How do I make an IntelliJ Idea task that builds, compiles, and outputs a jar file and json that I can put into my Minecraft launcher?

**Comment by Justsnoopy30** [comment]
Oh, sorry, didn't see the edit until now.

**Comment by Justsnoopy30** [comment]
Closed.

**Comment by ahmed605** [comment]
Answer 1: I will make a tutorial about this soon but I will give you some info about that :

1. Create Java Application in run Configuration name it "Client"
2.  set the Main Class to "mcp.client.Start"
3. set VM options to "-Xincgc -Xmx3024M -Xms3024M" (you can modify ram if you want)
4. set the Working dir to new folder for run you created (also if you want to copy minecraft assets to this folder do it this will fix the no sound problem)
5. set the Use classpath of module to "modern-mcp_main"
6. Click OK

**Comment by Justsnoopy30** [comment]
Ok.

**Comment by ahmed605** [comment]
Answer 2: you can run this gradle task modern-mcp->modern-mcp->Tasks->build->build to build the client you will find the jar in build/libs folder but the JSON file you must create it by your self

**Comment by Justsnoopy30** [comment]
Ok, setting up these tasks.

**Comment by ahmed605** [comment]
Oh in the Answer 1 you must add build Config in the Before Launch Section in Java Application(Client)

**Comment by Justsnoopy30** [comment]
I can't setup task 1.
When I put mcp.client.Start, nothing pops up and it glows red.

**Comment by Justsnoopy30** [comment]
Still, Warning: Class 'mcp.client.Start' not found in module 'modern-mcp.main'.

**Comment by ahmed605** [comment]
> Still,
> **Warning: Class 'mcp.client.Start' not found in module 'modern-mcp.main'.**

This is my Config https://live.staticflickr.com/65535/48120603928_263b14b629_b.jpg yours must be like that

**Comment by Justsnoopy30** [comment]
I see 2 differences.
1. My mcp.client.Start is in red and the error above is there.
2. Under "use classpath of module", your's is modern-mcp_main.
Mine is modern-mcp.main.
There's no option with the underline.

**Comment by ahmed605** [comment]
Try Browse the Main class from the ... button 
Try Change the use classpath of module to anything else

**Comment by Justsnoopy30** [comment]
I tried changing the classpath to all other options already.
I tried browsing to the main class but it wouldn't let me select.

**Comment by ahmed605** [comment]
> I tried browsing to the main class but it wouldn't let me select.

How?

**Comment by ahmed605** [comment]
Send a screenshot

**Comment by Justsnoopy30** [comment]
Oh, I was already doing that.

**Comment by Justsnoopy30** [comment]
![Screenshot 2019-06-24 at 9 58 55 AM](https://user-images.githubusercontent.com/33374736/60029464-cfe17280-9666-11e9-91a4-f256a7922aa5.png)

**Comment by Justsnoopy30** [comment]
Brb in 30 minutes.

**Comment by ahmed605** [comment]
The issue was the java (src->main->java) folder not set as (Marked as Sources root) to do that right click on it and press on Mark DIR as -> Sources Root
![Untitlbbbbbbbbbbbed](https://user-images.githubusercontent.com/34550324/60029943-5ebfb080-96a2-11e9-9e18-20aca332e217.png)

**Comment by Justsnoopy30** [comment]
> The issue was the java (src->main->java) folder not set as (Marked as Sources root) to do that right click on it and press on Mark DIR as -> Sources Root
> ![Untitlbbbbbbbbbbbed](https://user-images.githubusercontent.com/34550324/60029943-5ebfb080-96a2-11e9-9e18-20aca332e217.png)

Oh, do I also have to remove "main" from being a sources root?

**Comment by ahmed605** [comment]
No your main Folder is not marked as Sources Root

**Comment by ahmed605** [comment]
did the mcp.client.Start worked after doing this

**Comment by Justsnoopy30** [comment]
I'm having lunch right now so I can't test yet, I'm on my phone.

**Comment by ahmed605** [comment]
Ok tell me the result after doing this

**Comment by Justsnoopy30** [comment]
Also, there's a blue box icon next to the folder icon of folder main, meaning it is marked as a sources root, but I did not add it. Should I remove it and add the Java folder as the sources root or keep main as a sources root and add the Java folder as another sources root?

**Comment by ahmed605** [comment]
keep main as it was BTW the blue icon means that it has java sources inside it(Not Sources Root).

**Comment by Justsnoopy30** [comment]
Ok, I will try after lunch in 10 minutes.

**Comment by Justsnoopy30** [comment]
How quickly is mcp config updated?

**Comment by ahmed605** [comment]
> How quickly is mcp config updated?

What do you mean?

**Comment by Justsnoopy30** [comment]
The mappings, so this can be updated to 1.14.3.

**Comment by ahmed605** [comment]
> The mappings, so this can be updated to 1.14.3.

- The MCP mappings still at 1.14.2 : http://export.mcpbot.bspk.rs/

- The MCPConfig still at 1.14.2 : https://github.com/MinecraftForge/MCPConfig

**Comment by Justsnoopy30** [comment]
Ok

**Comment by Justsnoopy30** [comment]
Will test the fix in 4 minutes.

**Comment by ahmed605** [comment]
BRB in around 1h 30m

**Comment by Justsnoopy30** [comment]
Ok, I am now on, testing fix.

**Comment by Justsnoopy30** [comment]
I'm gonna create a new issue about the sound.

**Comment by ahmed605** [comment]
did the problem fixed

**Comment by Justsnoopy30** [comment]
Oh you're back @ahmed605

**Comment by Justsnoopy30** [comment]
Yes

**Comment by Justsnoopy30** [comment]
I opened another issue

**Comment by ahmed605** [comment]
Can you help me creating wiki for this tool

**Comment by Justsnoopy30** [comment]
@ahmed605 Sorry I didn't respond, I was out.
Sure, mention me when you respond.

**Comment by ahmed605** [comment]
@Justsnoopy30 I'm new at creating Github wikis so can you make a pull request that have simple wiki that have some info and answers to questions that were in this issue

**Comment by ahmed605** [comment]
@Justsnoopy30 I created pre 1.14.3 branch and I will make the final one when the 1.14.3 mappings get released!

**Comment by Justsnoopy30** [comment]
Ok

**Comment by Justsnoopy30** [comment]
@ahmed605 Check https://github.com/Justsnoopy30/Modern-MCP

**Comment by Justsnoopy30** [comment]
You cannot pull request a wiki.

**Comment by ahmed605** [comment]
https://github.com/ahmed605/Modern-MCP/invitations

**Comment by Justsnoopy30** [comment]
Ok

**Comment by Justsnoopy30** [comment]
I forked yours and added some GitHub improvements by the way.

**Comment by Justsnoopy30** [comment]
@ahmed605 I gtg, I will be on tomorrow.

**Comment by Justsnoopy30** [comment]
Nevermind, I will be on for 20 more minutes then I will be on more tomorrow.

**Comment by ahmed605** [comment]
@Justsnoopy30 Why i can't change the settings of Modern MCP team https://github.com/orgs/hypercubemc-github/teams/modern-mcp

**Comment by Justsnoopy30** [comment]
@ahmed605 Hold on, I'm setting up permissions now.

**Comment by Justsnoopy30** [comment]
@ahmed605 I added you as a maintainer of the team.

**Comment by ahmed605** [comment]
@Justsnoopy30 what do you think of the new Modern MCP logo
