### ISSUE TITLE
Add Task to Download Assets

### ISSUE THREAD

**Issue by Justsnoopy30** [ahmed605/Modern-MCP#3]
Sound when started in IntelliJ Idea Issue

**Comment by Justsnoopy30** [comment]
Where are the assets files in Modern-MCP located so I can copy them to my test Minecraft working directory for starting Minecraft with IntelliJ Idea?

**Comment by ahmed605** [comment]
I said to you before to fix this you have to copy assets from your minecraft to the run path

**Comment by ahmed605** [comment]
Unfortunately modern-mcp not downloading assets but I will fix this

**Comment by Justsnoopy30** [comment]
> Unfortunately modern-mcp not downloading assets but I will fix this

Soon?

**Comment by ahmed605** [comment]
As Soon As Possible!

**Comment by Justsnoopy30** [comment]
Ok

**Comment by Justsnoopy30** [comment]
Should we add the enhancement label to this?

**Comment by ahmed605** [comment]
@Justsnoopy30 this is strange but the assets auto downloaded when running with eclipse by using this commands: gradlew assemble --> gradlew setup --> gradlew eclipse and importing the gradle project to eclipse using this plugin http://makble.com/how-to-import-gradle-project-into-eclipse

**Comment by Justsnoopy30** [comment]
Saw this going to bed, will test tomorrow.

**Comment by ahmed605** [comment]
@Justsnoopy30 you must run `gradlew genIntellijRuns`
