### ISSUE TITLE
Cannot get to work with Eclipse.

### ISSUE THREAD

**Issue by tylastrog** [ahmed605/Modern-MCP#8]
When I set up Modern-MCP with Eclipse, I do this:

Command Prompt:
gradlew assemble, gradlew setup, gradlew eclipse, gradlew genEclipseRuns. (in that order)

Everything is successful, but when I run xxx_client.launch, an error is sent to the Eclipse console.

ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console. Set system property 'org.apache.logging.log4j.simplelog.StatusLogger.level' to TRACE to show Log4j2 internal initialization logging.

I've tried to add the log4j2.xml file to the resources but nothing happens in Eclipse after I do that.

Is there something I am doing wrong? Cheers!

**Comment by ahmed605** [comment]
how do you imported Modern MCP to Eclipse

**Comment by tylastrog** [comment]
Yes

**Comment by ahmed605** [comment]
> Yes

I mean how?

**Comment by tylastrog** [comment]
Oh, my bad. I right click in the navigation and select Import project, then I select the folder that contains my gradle.build, etc. Then it imports everything.

**Comment by ahmed605** [comment]
Hang on, I will test it

**Comment by ahmed605** [comment]
you must install Gradle plugin for eclipse tutorial: http://kaczanowscy.pl/tomek/2010-03/gradle-ide-integration-eclipse-plugin

**Comment by ahmed605** [comment]
Or from here : http://makble.com/how-to-import-gradle-project-into-eclipse

**Comment by tylastrog** [comment]
Okay, I have it imported. Do I just run setup in the mcp folder? (under gradle tasks)

**Comment by ahmed605** [comment]
yes and if worked close the issue

**Comment by tylastrog** [comment]
Okay, not sure if this is a PC issue but I'm getting an error in the Gradle Executions after I start runClient.

Process 'command 'D:\Program Files\Java\jre1.8.0_211\bin\java.exe'' finished with non-zero exit value 1

Originally it had said that it was missing tools.jar, so I copy and pasted it from my jdk folder. I then received that error.

**Comment by ahmed605** [comment]
I don't know but it worked with me 
![Untitledggggggggggggg](https://user-images.githubusercontent.com/34550324/60221517-473b2000-987a-11e9-94cf-604ca00eb848.png)

**Comment by tylastrog** [comment]
I just tried this with your release of 1.14.2 and it worked great. Is it an issue with the 1.14.3 release?

**Comment by ahmed605** [comment]
> I just tried this with your release of 1.14.2 and it worked great. Is it an issue with the 1.14.3 release?

send the log file

**Comment by tylastrog** [comment]
[console_log.txt](https://github.com/ahmed605/Modern-MCP/files/3332362/console_log.txt)

**Comment by ahmed605** [comment]
don't run task : runClient use the Eclipse Configuration that you can find here:
![Untitledfgfdgdfgd](https://user-images.githubusercontent.com/34550324/60224606-6e4a1f80-9883-11e9-8fd9-5d6c4dff0ba2.png)

**Comment by tylastrog** [comment]
Got it. Thanks!
